version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: movie-booking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movie_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movie_booking"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: movie-booking-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moviebooking.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: movie-booking-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data  

volumes:
  postgres_data:
  redis_data: